### ISSUE TITLE
Question: module incompatibility?

### ISSUE THREAD

**Issue by SR5060** [manuelVo/foundryvtt-lichtgeschwindigkeit#1]
Love the idea of better performance, do you anticipate issues /have you tested with any of the main lighting modules?

**Comment by manuelVo** [comment]
I'm aware that the "Wall Height" module currently doesn't work with Lichtgeschwindigkeit. Perfect Vision works with Lichtgeschwindigkeit. Other than that I have no info on compatibilities or incompatibilities of the module. I expect Lichtgeschwindigkeit to work well with most other vision modules, because the part of foundry that Lichtgeschwindigkeit changes is unlikely to be touched by other modules.

**Comment by Nordiii** [comment]
Ah dang, Lichtgeschwindigkeit + wall height probably crashed my session yesterday to the point where I needed to reboot the server (after around an hour of gametime on a map with wallheight walls).

Would there be a way for the author of wall height to add compability as your module is not open source?

**Comment by manuelVo** [comment]
Lichtgeschwindigkeit and Wall Height in combination shouldn't cause any crashes. The only incompatibility know to me is that every wall is reated to reach from -Infitity to Infinity, which means Wall Height essentieally ceases to function when Lichtgeschwindigkeit is enabled.

There is nothing the author of Wall Height can change in their module to reach compatibility. Making the modules compatible is completely up to me. I've created an separate issue to track compatibility with Wall Height. https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/issues/2

**Comment by Nordiii** [comment]
Mhm I just added your module to the Session since the one before but after moving a lot I had issues with the server basically freezing when trying to drag a token, because of this I assumed it would be this module (no errors in the console though).
Gonna investigate more at the weekend when I find time.

**Comment by manuelVo** [comment]
Lichtgeschwindigkeit can in theory cause freezes while dragging a token if something catastrophic goes wrong during lighting calculation. However if this happens, Lichtgeschwindigkeit will always log an error to the console.

**Comment by dev7355608** [comment]
Another candidate for conflicts is *Your Tokens Visible*. David-Zvekic/TokensVisible#13

**Comment by manuelVo** [comment]
To keep things manageable, please open a separate issue for each conflicting module. [I've created an issue to track the incompatibility with TokensVisible](https://github.com/manuelVo/foundryvtt-lichtgeschwindigkeit/issues/9)
