### ISSUE TITLE
Use `SourcePolygon` instead of `PIXI.Polygon` in FVTT 0.8.0+

### ISSUE THREAD

**Issue by dev7355608** [manuelVo/foundryvtt-lichtgeschwindigkeit#8]
FVTT 0.8.0 introduced the [SourcePolygon](https://foundryvtt.com/api/SourcePolygon.html).

**Comment by manuelVo** [comment]
Thanks for the hint. Looks like Lichtgeschwindigkeit should use this as well (maybe it's even worth backporting to 0.7...)

**Comment by manuelVo** [comment]
Lichtgeschwindigkeit now contains it's own improvements for `PIXI.Polygon`, which outperform `SourcePolygon`, so those will be used instead. Additionally those improvements will be applied to all `PIXI.Polygon`s, so other parts of foundry (or foundry modues) that use `PIXI.Polygon`s will profit from those improvements as well.

**Comment by dev7355608** [comment]
I think, Lichtgeschwindigkeit's `computePolygon` should return `SourcePolygon` as it and it's `x`/`y`/`radius` properties might be expected now by other modules.

Also, since `PIXI.Polygon` is patched, other modules that modify/substitute los/fov polygons could create a `SourcePolygon` instead of just a `PIXI.Polygon`; this `SourcePolygon` would now do both the radial and the box check.

Maybe it's better to just patch `SourcePolygon` and not `PIXI.Polygon`.

**Comment by manuelVo** [comment]
In theory you're right. However I think in practice other modules won't care about the `x`, `y`, `radius` properties. `x` and `y` are the coordinates of the token or light source - there other modules will probably access the position of the token/light source directly instead of trying to read it from the vision polygon. `radius` contains the vision range, which can be read from the token/light source as well. I also see no good reason why a module should be checking for the `SourcePolygon` type.

You're right about the possibility that other modules might be using the SourcePolygon class and would then perfor both checks. Ultimately the box check is so ridiculously cheap (not the first time it's performed because it has to gather data first, but every check after that - and things that are only executed once usually don't impact performance in a relevant way) that doing both checks wouldn't hurt too much. And as above this would only happen in the rare case that any module actually uses the `SourcePolygon` class (which I heavily doubt).

Those potential problems themselves can be fixed relatively easily. I could just return a `SourcePolygon` and patch the `contains` .function of that class as well. However Lichtgeschwindigkeit does still support Foundry 0.7 (which doesn't have the Source Polygon) and to add support for that I'd either need to drop 0.7 support or add a version check and build a separate code path. I'm not very eager to either of those two options just to fix an issue that could theoretically happen at some point in the future (being very unlikely to happen at all). Instead I prefer to see how things pan out and fix those issues should they actually crop up at some point.

**Comment by dev7355608** [comment]
In Perfect Vision I use `SourcePolygon`, but the impact isn't high as you said and I don't need the properties.

I realized yesterday that the containment check for source polygons can be optimized by ~400% after the box check can't rule out containment. Because of the shape of the polygon we only have to consider one quadrant of the polygon: meaning we have to run the even-odd rule algorithm only on one quarter of the polygon. So that would be a better reason to use `SourcePolygon` and completely replace its `contains` method.

**Comment by manuelVo** [comment]
Well that happened quickly... I'll have a look at how to best solve this.

**Comment by manuelVo** [comment]
Perfect Vision no longer uses `SourcePolygon` when Lichgeschwindigkeit is enabled, so this conflict is now resolved.
